// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBUP6v5Q7_K-pq76aTdkEzhfrFQ8sYZAFI",
      authDomain: "mtecgram.firebaseapp.com",
      projectId: "mtecgram",
      storageBucket: "mtecgram.appspot.com",
      messagingSenderId: "863939220031",
      appId: "1:863939220031:web:556eeafc0637a070c51e8a",
      measurementId: "G-VCWP9R5FCE");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzN7i1J7uYbmyKFCjvSThAU8JvGYoQri4',
    appId: '1:863939220031:android:5ba6a50fb109dd84c51e8a',
    messagingSenderId: '863939220031',
    projectId: 'mtecgram',
    storageBucket: 'mtecgram.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOYbQiUZF4xedWTxmbM1QliXyWxs2Dq0E',
    appId: '1:863939220031:ios:5526c180809cbcfbc51e8a',
    messagingSenderId: '863939220031',
    projectId: 'mtecgram',
    storageBucket: 'mtecgram.appspot.com',
    iosBundleId: 'com.example.smtecgram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOYbQiUZF4xedWTxmbM1QliXyWxs2Dq0E',
    appId: '1:863939220031:ios:8b4fc5f120202e41c51e8a',
    messagingSenderId: '863939220031',
    projectId: 'mtecgram',
    storageBucket: 'mtecgram.appspot.com',
    iosBundleId: 'com.example.smtecgram.RunnerTests',
  );
}
